version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'library'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
       MYSQL_HOST: 'db'
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/online_library
    ports:
      - "8000:8000"
    depends_on:
      - db