# Generated by Django 2.1.4 on 2019-01-06 20:23

import books.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190101_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to=books.helper.rename_and_path, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='e_pub',
            field=models.FileField(blank=True, upload_to=books.helper.rename_and_path, verbose_name='EPUB'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, upload_to=books.helper.rename_and_path, verbose_name='PDF'),
        ),
    ]
